services:
  gomud:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /.
    ports:
      - 3000:3000
    environment:
      - ENV_A=${ENV_A}
      - ENV_B=${ENV_B}
      - ENV_C=${ENV_C}
    volumes:
      - ./project-relative-path/:/project-package/